repos:


-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types:
        - python
        args:
        - --line-length=200
        - --target-version=py312
    
-   repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    -   id: flake8
        entry: flake8
        language: python
        language_version: python3.12	
        types:
        - python  
        
-   repo:   https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
    -   id: isort
        entry: isort
        language: python
        language_version: python3.12
        types: 
        - python
        
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        language_version: python3.12	
        types:
        - python
