version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      - DB_HOST=postgres
    ports:
      - "8000:8080"
    entrypoint: ["sh", "/app/entrypoint.sh"]
    volumes:
      - ./todo_core:/app/todo_core

volumes:
  postgres_data: