version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    ports:
      - "$POSTGRES_OUTER_PORT:$POSTGRES_PORT"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
 

  django:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      - DB_HOST=postgres
    ports:
      - "8000:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://$WEB_HOST:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: ["sh", "/app/entrypoint.sh"]
    volumes:
      - ./todo_core:/app/todo_core

volumes:
  postgres_data: