version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    restart: always
    depends_on:
      - db
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8080"
    volumes:
      - .:/app

volumes:
  postgres_data: