name: todo-core
run-name: run linters for django project
on: [push, pull, pull_request]
jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    with:
      python-version: "3.12"
      
    - name: run flake8
      run: |
          pip install flake8
          flake8 . --max-line-length=127
    - name: check black      
      run: |
          pip install black
          black . --check

    - name: check mypy
      run: |
         pip install mypy
         mypy .

      
    - name: check isort
      run: |
         pip install isort
         isort .
