# Generated by Django 5.1 on 2025-02-04 12:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcollaborators",
            name="role",
            field=models.CharField(
                choices=[("R", "Reader"), ("E", "Editor")], default="R", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
