# Generated by Django 5.1 on 2025-02-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectcollaborators_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcollaborators",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborators",
                to="projects.project",
            ),
        ),
    ]
