# Generated by Django 5.1 on 2025-02-04 07:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("d688bdac-16a4-4e03-916e-4635cd5df777"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TD", "To do"),
                            ("P", "In progress"),
                            ("C", "Complete"),
                        ],
                        default="TD",
                        max_length=2,
                    ),
                ),
                ("deadline", models.DateTimeField(default=None)),
                ("assigner_id", models.UUIDField(default=None)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskStatusSubscribers",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tasks.task",
                    ),
                ),
                ("user_id", models.UUIDField()),
            ],
            options={
                "db_table": "task_status_subscribers",
                "unique_together": {("task_id", "user_id")},
            },
        ),
    ]
