# Generated by Django 5.1 on 2025-02-04 09:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1f2c4967-438e-451e-a64c-adb6645ff55d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
