# Generated by Django 5.1 on 2025-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigner_id",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
