# Generated by Django 5.1 on 2025-02-24 11:21
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_assigner_id_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatussubscribers",
            name="task_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="taskstatussubscribers",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, serialize=False, null=True),
        ),
    ]
