# Generated by Django 5.1 on 2025-02-24 11:21

import uuid
from typing import Any

from django.db import migrations


def gen_uuid(apps: Any, schema_editor: Any) -> None:
    TaskStatusSubscribers = apps.get_model("tasks", "TaskStatusSubscribers")
    for row in TaskStatusSubscribers.objects.all():
        row.id = uuid.uuid4()
        row.save(update_fields=["id"])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_auto_20250224_1121"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
