# Generated by Django 5.1 on 2025-02-24 11:21


import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_auto_20250224_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatussubscribers",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
