name: CI Pipeline

on: [push, pull_request] 

jobs:
  build:
    name: Build Project with Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Create .env file in porject folder
        run: |
          echo "${{ secrets.dotenv }}" > .env

      - name: Set up Docker Compose
        run: docker-compose up --build -d

  linters:
    name: Run python linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run mypy
      uses: jpetrucciani/mypy-check@master
      with:
        path: 'todo_core/'
        python_version: "3.12"
    
    - name: Run isort
      uses: davidslusser/actions_python_isort@v1.0.1

    - name: Run black formater
      uses: lgeiger/black-action@master

    - name: Run flake8-cq
      uses: reactive-firewall/flake8-cq@master
      with:
        config: "setup.cfg"  # Specify the Flake8 configuration file
        path: "todo_core/"