name: CI Pipeline

on: [push, pull_request] 

jobs:
  build:
    name: Build Project with Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Create .env file in porject folder
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "PYTHONUNBUFFERED=1" >> .env
          echo "WEB_HOST={{ secrets.WEB_HOST}}" >> .env
          
      - name: Set up Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services to be healthy
        run: sleep 10

      - name: Check running containers
        run: docker ps -a

  flake8:
    name: Run Flake8 Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 --config setup.cfg .

  isort:
    name: Run Isort Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install isort

      - name: Run Isort
        run: isort --check-only .

  black:
    name: Run Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install black

      - name: Run Black
        run: black .

  mypy:
    name: Run MyPy Type Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install mypy

      - name: Run MyPy
        run: mypy --config-file setup.cfg .
