name: CI Pipeline

on:
  pull_request:
    branches: 
      - dev
      - main
  push:

jobs:
  build:
    name: Build Project with Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Set up Docker Compose
        run: docker compose --env-file .env.example up --build -d

  linters:
    name: Run python linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run mypy
      uses: jpetrucciani/mypy-check@master
      with:
        path: 'todo_core/'
        python_version: "3.12"
    
    - name: Run isort
      uses: isort/isort-action@v1

    - name: Run black formater
      uses: lgeiger/black-action@master

    - name: Run flake8-cq
      uses: reactive-firewall/flake8-cq@master
      with:
        config: "setup.cfg"
        path: "todo_core/"